language: node_js
#  latest stable Node.js release
node_js: lts/*
addons:
  chrome: stable # make Chrome available
# Cache node packages between jobs
cache: npm

script:
  - npm run lint
  # - npm run test
  - npm run generate:modern
  - cp -R dist public
  - npx semantic-release

deploy:
  - provider: surge
    domain: daim.dev
    project: ./public
    edge: true # opt in to dpl v2
    on:
      branch: master

  - provider: surge
    domain: staging.daim.dev
    project: ./public
    edge: true # opt in to dpl v2
    on:
      all_branches: true

after_success:
  - npm run lhci:autorun
