version: "3"

services:
  nuxt:
    build: .
    container_name: daim-website
    restart: unless-stopped
    ports:
      - "3000:3000"
    command:
      "yarn dev"
    volumes:
      - ./:/src:cached
    networks:
      - proxy

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:2023.3.1
    restart: unless-stopped
    command: tunnel
    networks:
      - proxy
    depends_on:
      - daim-website
    environment:
      TUNNEL_URL: http://daim-website:3000

  imgproxy:
    image: darthsim/imgproxy:latest
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - IMGPROXY_MAX_SRC_RESOLUTION=50
      - IMGPROXY_KEY=${IMGPROXY_KEY}
      - IMGPROXY_SALT=${IMGPROXY_SALT}
    networks:
      - proxy

networks:
  proxy:
    driver: bridge
