version: "3"

services:
  nuxt:
    build: .
    container_name: daim-website
    restart: unless-stopped
    ports:
      - "3000:3000"
    command:
      "npm run dev"
    volumes:
      - ./:/src:cached

  nginx:
    image: nginx:latest
    container_name: daim-nginx
    restart: unless-stopped
    ports:
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - nuxt

  imgproxy:
    image: darthsim/imgproxy:latest
    restart: unless-stopped
    ports: 
      - 8080:8080
    environment:
      - IMGPROXY_MAX_SRC_RESOLUTION=50
