version: "3"

services:
  playwright:
    image: mcr.microsoft.com/playwright:v1.40.0-jammy
    command: /bin/bash
    network_mode: host
    volumes:
      - ${PWD}:/work/
    working_dir: /work/
    container_name: playwright

  nuxt:
    build: .
    container_name: daim-website
    # restart: unless-stopped
    ports:
      - "3000:3000"
      - "5678:5678"
    command: yarn dev
    volumes:
      - ./:/src
    networks:
      - daim

  tunnel:
    container_name: cloudflared-tunnel
    image: cloudflare/cloudflared:2023.3.1
    # restart: unless-stopped
    command: tunnel
    networks:
      - daim
    depends_on:
      - nuxt
    environment:
      TUNNEL_URL: http://nuxt:3000


  imgproxy:
    image: darthsim/imgproxy:latest
    # restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      - IMGPROXY_ENABLE_CLIENT_HINTS=true
      - IMGPROXY_ALLOW_ORIGIN=*
      - IMGPROXY_MAX_SRC_RESOLUTION=50
      - IMGPROXY_KEY=${IMGPROXY_KEY}
      - IMGPROXY_SALT=${IMGPROXY_SALT}
    networks:
      - daim

networks:
  daim:
    driver: bridge
